version: "3.3"
services:
  es-node:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9200"]
        interval: 30s
        timeout: 10s
        retries: 5
  kb-es-01:
    image: docker.elastic.co/kibana/kibana:7.15.1
    depends_on:
      - es-node
    environment:
      - ELASTICSEARCH_HOSTS="http://es-node:9200"
      - elasticsearch.username="kibana_system"
      - elasticsearch.password="123456"
    ports:
      - 5601:5601
    networks:
      - elastic

volumes:
  data01:
    driver: local
  

networks:
  elastic:
    driver: bridge
